### PR TITLE
Syntax Correction rgb ( to rgb(

### PR DESCRIPTION
**Pull request by eyllanesc**
The problem was the space in the StyleSheet instructions, for example:

`"background-color: rgb(255,0,0); color: rgb (10,10,10);"`

You should change it to:

`"background-color: rgb(255,0,0); color: rgb(10,10,10);"`

Without that space. If you place an instruction incorrectly Qt will not recognize it and will not place it.

Another thing, some slots were with an incorrect name, these have already corrected.

### CODE REVIEW

**Comment by HWerneck** [comment]
What a stupid thing to incapacitate a program. -.-'
It's a habbit to type using spaces between the word, function, whatever and the parethesis.
Also, what slots were with incorrect names? What is this slot/signal thing?

**Comment by HWerneck** [comment]
By the way, thanks a ton! I've tried to do this twice in the past,  unsuccessfully.

**Comment by eyllanesc** [comment]
You have made a mistake, do not criticize the bookstore if you are just a beginner. One thing a teacher told me: The machine is silly, but we are intelligent.

When you generate slots with Qt Designer it uses the [connectSlotsByName](http://doc.qt.io/qt-4.8/qmetaobject.html#connectSlotsByName) method and it has a particular syntax, please read the documentation. Learning to understand is important to any developer.

**Comment by HWerneck** [comment]
> You have made a mistake, do not criticize the bookstore if you are just a beginner.
If you mean criticize by this "What a stupid thing to incapacitate a program. -.-'", I'm not criticizing.
I just meant that it was such a simple thing as a "space" that would make a whole function unusable.
But that's syntax. It's like not typing ";" at the end of a line. It won't compile, but it's not fault of the functions you are using, libraries and stuff. It's just the way you have to type it. =P

**Pull request closed without merging**
